/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#baeed5",
        "on-primary-fixed": "#0b1f1a",
        tertiary: "#000000",
        "surface-container-lowest": "#ffffff",
        "tertiary-container": "#002116",
        "surface-container-low": "#f6f3f2",
        "surface-container-highest": "#e5e2e1",
        "on-primary-fixed-variant": "#374b44",
        "surface-variant": "#e5e2e1",
        "outline-variant": "#c2c8c4",
        primary: "#000000",
        "surface-container": "#f0edec",
        "secondary-container": "#50fec1",
        "on-secondary-fixed": "#002115",
        "surface-dim": "#dcd9d9",
        background: "#fcf9f8",
        "on-background": "#1c1b1b",
        "surface-tint": "#4e635c",
        error: "#ba1a1a",
        "primary-fixed": "#d1e8df",
        "on-tertiary-fixed-variant": "#1e4f3d",
        "on-primary": "#ffffff",
        secondary: "#006c4d",
        "on-tertiary": "#ffffff",
        "on-primary-container": "#738881",
        "on-tertiary-container": "#5d8e79",
        "error-container": "#ffdad6",
        "on-secondary-container": "#007352",
        "inverse-on-surface": "#f3f0ef",
        "on-error-container": "#93000a",
        "secondary-fixed": "#50fec1",
        outline: "#727875",
        "on-tertiary-fixed": "#002116",
        "on-surface": "#1c1b1b",
        "on-secondary": "#ffffff",
        "surface-container-high": "#ebe7e7",
        surface: "#fcf9f8",
        "primary-fixed-dim": "#b5cbc3",
        "primary-container": "#0b1f1a",
        "surface-bright": "#fcf9f8",
        "inverse-surface": "#313030",
        "tertiary-fixed-dim": "#9fd1ba",
        "on-surface-variant": "#424845",
        "inverse-primary": "#b5cbc3",
        "on-secondary-fixed-variant": "#005139",
        "on-error": "#ffffff",
        "secondary-fixed-dim": "#1fe1a6",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        lg: "24px",
        sm: "8px",
        gutter: "20px",
        xs: "4px",
        md: "16px",
        "container-margin": "24px",
        xl: "32px",
        base: "4px",
      },
      fontFamily: {
        "headline-lg-mobile": ["Inter"],
        "body-md": ["Inter"],
        "title-lg": ["Inter"],
        "headline-md": ["Inter"],
        "headline-lg": ["Inter"],
        "display-lg": ["Inter"],
        "body-lg": ["Inter"],
        "label-md": ["Inter"],
      },
      fontSize: {
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "title-lg": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-lg": ["28px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "display-lg": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
      },
    },
  },
  plugins: [require("@tailwindcss/forms")],
};
